'use strict';
// ═══════════════════════════════════════════
// NOMANDA CLI — Research mode
// Deep multi-pass research on a topic, saved
// as markdown in ~/.nomanda/research/
// ═══════════════════════════════════════════
import path from 'node:path';
import { PATHS, writeFileSafe, stamp } from './store.js';
import { streamChat } from './brain.js';
import { c, say, spin, stopSpin } from './ui.js';

const PASSES = [
  ['Overview', 'Give a clear overview of the topic: what it is, why it matters, current state.'],
  ['Key facts & findings', 'List the most important facts, numbers and findings as bullets.'],
  ['Different angles', 'Analyse it from 3 different perspectives (technical, economic, social).'],
  ['Sources to check', 'List the best sources (sites, papers, orgs) someone should verify this against.'],
  ['Bottom line', 'Give a 3-sentence bottom-line conclusion.'],
];

export async function runResearch(args) {
  const topic = args.join(' ').trim();
  if (!topic) { say.err('usage: research <topic>'); return; }

  const parts = [];
  const started = Date.now();
  for (const [title, prompt] of PASSES) {
    say.info(`researching · ${title}`);
    spin(title.toLowerCase());
    try {
      const { text } = await streamChat([
        { role: 'system', content: `You are NOMANDA Research. Be factual, specific and concise. Topic: ${topic}` },
        { role: 'user', content: prompt }
      ]);
      stopSpin();
      parts.push(`## ${title}\n\n${text.trim()}\n`);
      console.log(c.dim(text.trim().split('\n').slice(0, 3).map(l => '    ' + l).join('\n')));
    } catch (e) {
      stopSpin();
      say.err(`${title} failed: ${e.message}`);
      parts.push(`## ${title}\n\n_(unavailable: ${e.message})_\n`);
    }
  }

  const md = `# Research: ${topic}\n\n> generated by NOMANDA CLI · Frabula 1.2 · ${new Date().toISOString()}\n\n${parts.join('\n')}`;
  const file = path.join(PATHS.research, `${topic.toLowerCase().replace(/\W+/g, '-').slice(0, 40)}-${stamp()}.md`);
  writeFileSafe(file, md);

  console.log('\n' + c.bold(c.accent('─── REPORT ───')));
  for (const p of parts) {
    const [head, ...rest] = p.split('\n\n');
    console.log(c.accent2('\n' + head));
    console.log(rest.join('\n\n').trim());
  }
  console.log('');
  say.ok(`saved · ${file} · ${((Date.now() - started) / 1000).toFixed(1)}s`);
}
